-- ============================================================
-- Plan Groups & Plans Schema
-- Run this in the Supabase SQL Editor
-- ============================================================

-- Plan Groups (Standard, Premium Small, 1-on-1 Private)
CREATE TABLE IF NOT EXISTS plan_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  max_students int, -- NULL means unlimited / 1-on-1
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Individual Plans (tiers within each group)
CREATE TABLE IF NOT EXISTS plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_group_id bigint REFERENCES plan_groups(id) ON DELETE CASCADE,
  classes_per_month int NOT NULL,          -- 8, 12, or 16
  price_monthly numeric(10,2) NOT NULL,
  price_12months numeric(10,2) NOT NULL,
  price_6months numeric(10,2) NOT NULL,
  price_3months numeric(10,2) NOT NULL,
  free_classes_12months int DEFAULT 16,
  free_classes_6months int DEFAULT 4,
  free_classes_3months int DEFAULT 1,
  is_popular boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Disable RLS (temporary, matching project convention)
ALTER TABLE plan_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE plans DISABLE ROW LEVEL SECURITY;

-- ============================================================
-- Seed: Plan Groups
-- ============================================================
INSERT INTO plan_groups (name, max_students) VALUES
  ('Standard Group Plan', 10),
  ('Premium Small Group Plan', 5),
  ('1-on-1 Private Plan', 1);

-- ============================================================
-- Seed: Standard Group Plan (id = 1) — 3 tiers
-- ============================================================
INSERT INTO plans (plan_group_id, classes_per_month, price_monthly, price_12months, price_6months, price_3months, is_popular)
SELECT id, 8,  80.00,  800.00,  440.00, 230.00, false FROM plan_groups WHERE name = 'Standard Group Plan';

INSERT INTO plans (plan_group_id, classes_per_month, price_monthly, price_12months, price_6months, price_3months, is_popular)
SELECT id, 12, 110.00, 1100.00, 605.00, 320.00, true  FROM plan_groups WHERE name = 'Standard Group Plan';

INSERT INTO plans (plan_group_id, classes_per_month, price_monthly, price_12months, price_6months, price_3months, is_popular)
SELECT id, 16, 135.00, 1350.00, 742.50, 396.00, false FROM plan_groups WHERE name = 'Standard Group Plan';

-- ============================================================
-- Seed: Premium Small Group Plan — 3 tiers
-- ============================================================
INSERT INTO plans (plan_group_id, classes_per_month, price_monthly, price_12months, price_6months, price_3months, is_popular)
SELECT id, 8,  110.00, 1100.00, 605.00, 320.00, false FROM plan_groups WHERE name = 'Premium Small Group Plan';

INSERT INTO plans (plan_group_id, classes_per_month, price_monthly, price_12months, price_6months, price_3months, is_popular)
SELECT id, 12, 135.00, 1350.00, 742.50, 396.00, false FROM plan_groups WHERE name = 'Premium Small Group Plan';

INSERT INTO plans (plan_group_id, classes_per_month, price_monthly, price_12months, price_6months, price_3months, is_popular)
SELECT id, 16, 160.00, 1600.00, 880.00, 470.00, false FROM plan_groups WHERE name = 'Premium Small Group Plan';

-- ============================================================
-- Seed: 1-on-1 Private Plan — 3 tiers
-- ============================================================
INSERT INTO plans (plan_group_id, classes_per_month, price_monthly, price_12months, price_6months, price_3months, is_popular)
SELECT id, 8,  220.00, 2200.00, 1210.00, 632.00, false FROM plan_groups WHERE name = '1-on-1 Private Plan';

INSERT INTO plans (plan_group_id, classes_per_month, price_monthly, price_12months, price_6months, price_3months, is_popular)
SELECT id, 12, 320.00, 3200.00, 1760.00, 933.00, false FROM plan_groups WHERE name = '1-on-1 Private Plan';

INSERT INTO plans (plan_group_id, classes_per_month, price_monthly, price_12months, price_6months, price_3months, is_popular)
SELECT id, 16, 410.00, 4100.00, 2255.00, 1204.00, false FROM plan_groups WHERE name = '1-on-1 Private Plan';

-- ============================================================
-- Add plan_id to batches table
-- ============================================================
ALTER TABLE batches
  ADD COLUMN IF NOT EXISTS plan_id bigint REFERENCES plans(id) ON DELETE SET NULL;
