-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  role text check (role in ('admin', 'teacher', 'student')) default 'student',
  first_name text,
  last_name text
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a trigger to automatically create a profile for new users
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, first_name, last_name, role)
  values (new.id, new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name', 'student');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create Courses table
create table courses (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Teachers table
create table teachers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  specialization text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Batches table
create table batches (
  id bigint generated by default as identity primary key,
  name text not null,
  course_id bigint references courses(id) on delete cascade,
  teacher_id bigint references teachers(id) on delete set null,
  start_date date,
  end_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create policies for Courses (Admins can do everything, others read-only)
alter table courses enable row level security;
create policy "Courses are viewable by everyone" on courses for select using (true);
create policy "Admins can insert courses" on courses for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update courses" on courses for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete courses" on courses for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Create policies for Teachers (Admins can do everything, others read-only)
alter table teachers enable row level security;
create policy "Teachers are viewable by everyone" on teachers for select using (true);
create policy "Admins can insert teachers" on teachers for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update teachers" on teachers for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete teachers" on teachers for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Create policies for Batches (Admins can do everything, others read-only)
alter table batches enable row level security;
create policy "Batches are viewable by everyone" on batches for select using (true);
create policy "Admins can insert batches" on batches for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update batches" on batches for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete batches" on batches for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- SEED DATA (Run this manually in SQL Editor if needed, or rely on creating the user via Auth API and then manually updating role)
-- Note: You cannot directly insert into auth.users via SQL easily due to password hashing. 
-- INSTRUCTION: Manually create a user with email 'admin@edu.com' and password 'admin123' in the Supabase Auth Dashboard.
-- THEN run this SQL to make them an admin:
-- update profiles set role = 'admin' where id = (select id from auth.users where email = 'admin@edu.com');
