-- Add plan_id to users to track their selected pricing plan
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS plan_id bigint REFERENCES public.plans(id) ON DELETE SET NULL;

-- Create enrollments table to track student-batch associations
CREATE TABLE IF NOT EXISTS public.enrollments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  batch_id bigint NOT NULL REFERENCES public.batches(id) ON DELETE CASCADE,
  enrolled_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, batch_id) -- Prevent double enrollment in the same batch
);

-- Disable RLS for enrollments to match the project's current temporary state
ALTER TABLE public.enrollments DISABLE ROW LEVEL SECURITY;
