-- Link teachers to users table for authentication
ALTER TABLE public.teachers
ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES public.users(id) ON DELETE SET NULL;

-- Create tests table for teachers to upload test materials
CREATE TABLE IF NOT EXISTS public.tests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id bigint NOT NULL REFERENCES public.batches(id) ON DELETE CASCADE,
  teacher_id bigint NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  file_url text NOT NULL, -- URL to the file in storage
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create test_submissions table for students to upload their answers
CREATE TABLE IF NOT EXISTS public.test_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id bigint NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  file_url text NOT NULL, -- URL to the answer file in storage
  submitted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  feedback text, -- Optional teacher feedback
  UNIQUE(test_id, student_id) -- Prevent multiple submissions for the same test by one student
);

-- Disable RLS for the new tables for now to match the project's temporary setup
ALTER TABLE public.tests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_submissions DISABLE ROW LEVEL SECURITY;
